name: Build with ncc 

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build with ncc
      run: npx @vercel/ncc build index.js -o dist

    - name: Commit and push if changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git add dist/index.js
        git diff --quiet && git diff --staged --quiet || git commit -m "Automated build"
        git push